// <auto-generated />
namespace WhatsIn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_UserId_Store : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_UserId_Store));
        
        string IMigrationMetadata.Id
        {
            get { return "201705021013393_Add_UserId_Store"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
